version: '2'
services:

  # The backend
  backend:
    build:
      context: ./
      dockerfile: backend.dockerfile
    working_dir: /var/www/backend
    volumes:
    - ../backend:/var/www/backend
    - ./ssl:/etc/nginx/ssl
    environment:
    - DB_PORT=3306
    - DB_HOST=database
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}

  # The frontend
  frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    working_dir: /var/www/frontend
    volumes:
    - ../frontend:/var/www/frontend
    - ./ssl:/etc/nginx/ssl
    user: ${DOCKER_USER_UID}:${DOCKER_USER_GID}
    command: tail -F anything

  # The Web Server
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
    - backend
    - frontend
    ports:
    - ${NGINX_HOST_HTTP_PORT}:80
    - ${NGINX_HOST_HTTPS_PORT}:443

  # MySQL
  database:
    image: mysql:5.7
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
    - ${MYSQL_PORT}:3306

volumes:
  dbdata:
